# Generated by Django 6.0.6 on 2026-06-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Oda Adı')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Açıklama')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Fiyat (₺)')),
                ('image', models.ImageField(upload_to='rooms/', verbose_name='Resim')),
            ],
            options={
                'verbose_name': 'Oda',
                'verbose_name_plural': 'Odalar',
            },
        ),
    ]
