# Generated by Django 6.0.6 on 2026-06-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Resim')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Galeri Resmi',
                'verbose_name_plural': 'Galeri Resimleri',
            },
        ),
    ]
