# Generated by Django 6.0.6 on 2026-06-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mains', 'Ana Yemek'), ('desserts', 'Tatlı'), ('drinks', 'İçecek')], max_length=20, verbose_name='Kategori')),
                ('name', models.CharField(max_length=100, verbose_name='Ürün Adı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Fiyat (₺)')),
            ],
            options={
                'verbose_name': 'Menü Öğesi',
                'verbose_name_plural': 'Menü Öğeleri',
            },
        ),
    ]
