# Generated by Django 6.0.6 on 2026-06-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, verbose_name='Yıl')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('icon', models.CharField(choices=[('ion-ios-business', 'Bina'), ('ion-ios-construct', 'Yenileme'), ('ion-ios-restaurant', 'Restoran'), ('ion-ios-star', 'Yıldız'), ('ion-ios-people', 'Kadro'), ('ion-ios-calendar', 'Takvim')], default='ion-ios-star', max_length=50, verbose_name='İkon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Tarihçe Olayı',
                'verbose_name_plural': 'Tarihçe',
                'ordering': ['order'],
            },
        ),
    ]
