# Generated by Django 6.0.6 on 2026-06-14 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_historyevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyevent',
            name='icon',
            field=models.CharField(choices=[('ion-ios-star', 'Yıldız'), ('ion-ios-home', 'Ev'), ('ion-ios-location', 'Konum'), ('ion-ios-telephone', 'Telefon'), ('ion-ios-email', 'Email'), ('ion-ios-calendar', 'Takvim'), ('ion-ios-people', 'Kadro'), ('ion-ios-checkmark-circle', 'Onay')], default='ion-ios-star', max_length=50, verbose_name='İkon'),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/extra/', verbose_name='Resim')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='myapp.room', verbose_name='Oda')),
            ],
            options={
                'verbose_name': 'Oda Resmi',
                'verbose_name_plural': 'Oda Resimleri',
            },
        ),
    ]
