# Generated by Django 6.0.6 on 2026-06-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_contactmessage_alter_roomimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(upload_to='homepage/', verbose_name='Hero Arka Plan Resmi')),
                ('hero_caption', models.CharField(default='YALVAÇ ÖĞRETMENEVİ', max_length=100, verbose_name='Üst Yazı')),
                ('hero_title', models.CharField(default='Konforlu ve Güvenilir Konaklama', max_length=200, verbose_name='Başlık')),
                ('welcome_image_1', models.ImageField(upload_to='homepage/', verbose_name='Hoş Geldiniz Resmi 1 (büyük)')),
                ('welcome_image_2', models.ImageField(upload_to='homepage/', verbose_name='Hoş Geldiniz Resmi 2 (üstte)')),
                ('welcome_title', models.CharField(default="Yalvaç Öğretmenevi'ne Hoş Geldiniz", max_length=200, verbose_name='Başlık')),
                ('welcome_text', models.TextField(verbose_name='Açıklama Yazısı')),
            ],
            options={
                'verbose_name': 'Anasayfa İçeriği',
                'verbose_name_plural': 'Anasayfa İçeriği',
            },
        ),
    ]
