# Generated by Django 6.0.6 on 2026-06-16 21:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_homepagecontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Duyuru', 'verbose_name_plural': 'Duyurular'},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='image',
        ),
        migrations.AddField(
            model_name='announcement',
            name='content',
            field=models.TextField(blank=True, default='', null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayınlanma Tarihi'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
    ]
