# Generated by Django 6.0.6 on 2026-06-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_announcement_options_remove_announcement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/', verbose_name='Duyuru Resmi'),
        ),
    ]
